User.create!(role: 1,
  nickname: "あど",
  email: "admin@admin.com",
  password: "7777777",
  password_confirmation: "7777777",
  name: "あどみん",
  name_kana: "アドミン",
  birth_date: "1930-01-01",
  prefecture_id: "14",
  city_block: "大津市",
  station: "大津駅",
)